# Generated by Django 5.1.4 on 2024-12-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_userprofile_age_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='genres',
            field=models.JSONField(default=list),
        ),
    ]
