# Generated by Django 5.1.4 on 2024-12-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
